name: Check Pull Request
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install poetry
        working-directory: ${{ matrix.lib }}
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        working-directory: ${{ matrix.lib }}
        run: poetry install
      - name: Run tests
        working-directory: ${{ matrix.lib }}
        run: poetry run python -m unittest discover -s tests -v
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
          SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}
