name: Check Commit
on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        working-directory: ${{ matrix.lib }}
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        working-directory: ${{ matrix.lib }}
        run: poetry install
      - name: Check format
        working-directory: ${{ matrix.lib }}
        run: poetry run black --check .

  typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        working-directory: ${{ matrix.lib }}
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        working-directory: ${{ matrix.lib }}
        run: poetry install
      - name: Check typing
        working-directory: ${{ matrix.lib }}
        run: poetry run mypy --install-types --non-interactive --strict $(echo "${{ matrix.lib }}" | tr "-" "_")

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        working-directory: ${{ matrix.lib }}
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        working-directory: ${{ matrix.lib }}
        run: poetry install
      - name: Check security
        working-directory: ${{ matrix.lib }}
        run: poetry run bandit -sB105 -r .

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        working-directory: ${{ matrix.lib }}
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        working-directory: ${{ matrix.lib }}
        run: poetry install
      - name: Run tests
        working-directory: ${{ matrix.lib }}
        run: poetry run python -m unittest discover -s tests -v
